project:
  type: website
  output-dir: docs

website:
  title: "ETC Eval"

  search: 
    location: navbar
    type: textbox


  navbar:
    search: true
    right:
      - href: index.qmd #main landing page
        text: Home
      - href: Contributors.md
        text: Contributors
      - href: 2024 Panel Validation.md
        text: Documentation
      
  sidebar: 
    - style: 'docked'
      search: true
      contents:
        - section: 'OpenLEDEval'
          contents: 
            - auto: Library
            - auto: Topics
        
format:
  html:
    theme: spacelab
    css: styles.css
    toc: false


